#pragma once

#define MAX_FILE_LEN 255
#define MAX_NAME_LEN 255
#define MAX_IP_LEN 24
#define MAX_DATE_LEN 22
#define MAX_CFG_LEN 4096

#define MAX_HEADERS 256

#define MAX_ALLOWED_HOSTS 30
#define MAX_ALLOWED_USER_AGENTS 30

#define MAX_THREADS 256