name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Update system packages
      run: sudo apt update
    - name: Install JSON-C packages
      run: sudo apt install -y git cmake doxygen valgrind
    - name: Build JSON-C
      run: make json-c
    - name: Install JSON-C
      run: sudo make json-c-install
    - name: Build web server
      run: make
    - name: Install web server
      run: sudo make install