name: Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Update and upgrade system packages
      run: |
        sudo apt update
        sudo apt upgrade -y
    - name: Install JSON-C packages
      run: sudo apt install -y git cmake doxygen valgrind
    - name: Build JSON-C
      run: make json-c
    - name: Install JSON-C
      run: sudo make json-c-install
    - name: Build web server
      run: make
    - name: Install web server
      run: sudo make install
    - name: Create basic config file
      run: echo '{ "bind_addr": "0.0.0.0", "bind_port": 8080 }' > ./conf.json
    - name: Run web server for 10 seconds
      run: cweb -t 10